drop table if exists member;
create table member (member_id bigint generated by default as identity, identify_token varchar(255), nickname varchar(255), profile_img varchar(255), primary key (member_id));

drop table if exists posts;
create table posts (id varchar(255) not null, content varchar(255), created_at timestamp, updated_at timestamp, disclosure boolean not null, first_category varchar(255), member_id bigint, second_category varchar(255), tags varchar(255), views integer not null, primary key (id));

drop table if exists folder;
create table folder (folder_id bigint generated by default as identity, created_at timestamp, updated_at timestamp, cover_img varchar(255), is_default boolean not null, member_id bigint, name varchar(255), primary key (folder_id));

drop table if exists folder_item;
create table folder_item (folder_item_id bigint generated by default as identity, created_at timestamp, updated_at timestamp, content varchar(255), disclosure boolean, first_category varchar(255), member_id bigint, post_id varchar(255), second_category varchar(255), tags varchar(255), folder_id bigint, primary key (folder_item_id));

drop table if exists search_entity;
create table search_entity (id varchar(255) not null, content varchar(255), created_at timestamp, first_category varchar(255), member_id bigint, second_category varchar(255), tags varchar(255), views integer not null, primary key (id));