spring:
  jwt:
    secret: jwt
  datasource:
    url: jdbc:mysql://localhost:3306/iam?serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect #org.hibernate.dialect.H2Dialect
#    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create
  response:
    success:
      code: 200
      msg: SUCCESS
    exceptions:
      custom1:
        code: 401
        msg: '토큰 정보가 유효하지 않습니다.'
        type: depromeet.ohgzoo.iam.jwt.UnAuthenticationException
      userNotExists:
        code: 401
        msg: '유저가 존재하지 않습니다. '
        type: depromeet.ohgzoo.iam.member.NoExistsMemberException
      postNotExists:
        code: 401
        msg: '글이 존재하지 않습니다. '
        type: depromeet.ohgzoo.iam.posts.PostsNotFoundException