spring:
  application:
    name: main
  profiles:
    active: local
  batch:
    job:
      enabled: false
  response:
    success:
      code: 200
      msg: SUCCESS
    exceptions:
      custom1:
        code: 401
        msg: '토큰 정보가 유효하지 않습니다.'
        type: depromeet.ohgzoo.iam.jwt.UnAuthenticationException
      userNotExists:
        code: 401
        msg: '유저가 존재하지 않습니다. '
        type: depromeet.ohgzoo.iam.member.NoExistsMemberException
      postNotExists:
        code: 401
        msg: '글이 존재하지 않습니다. '
        type: depromeet.ohgzoo.iam.posts.PostsNotFoundException
      accessDenied:
        code: 401
        msg: '접근 권한이 없습니다. '
        type: depromeet.ohgzoo.iam.posts.AccessDeniedException
      InvalidUser:
        code: 401
        msg: '권한이 없는 유저입니다. '
        type: depromeet.ohgzoo.iam.folder.InvalidUserException
      folderNotExists:
        code: 400
        msg: '폴더가 존재하지 않습니다. '
        type: depromeet.ohgzoo.iam.folder.NotExistsFolderException
      InValid:
        code: 403
        msg: '유효하지 않은 형식입니다. '
        type: depromeet.ohgzoo.iam.folder.ValidationException
      folderNameExists:
        code: 403
        msg: '이미 존재하는 폴더명이에요. '
        type: depromeet.ohgzoo.iam.folder.ExistedNameException
      folderItemNotExists:
        code: 400
        msg: '폴더에 해당 글이 존재하지 않습니다. '
        type: depromeet.ohgzoo.iam.folder.folderItem.NotExistsFolderItemException
      folderCannotDelete:
        code: 403
        msg: '삭제할 수 없는 폴더입니다. '
        type: depromeet.ohgzoo.iam.folder.ProtectedFolderException

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/