spring:
  jwt:
    secret: ${JWT_KEY}
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: ${DB_CONNECTION_STRING}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

kakaoClientId: ${KAKAO_CLIENT_ID}
kakaoRedirectUrl: ${KAKAO_REDIRECT_URL}

#logging:
#  level:
#    root: error
