spring:
  profiles:
    active: local
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  response:
    success:
      code: 200
      msg: SUCCESS
    exceptions:
      custom1:
        code: 401
        msg: '토큰 정보가 유효하지 않습니다.'
        type: depromeet.ohgzoo.iam.jwt.UnAuthenticationException
      userNotExists:
        code: 401
        msg: '유저가 존재하지 않습니다. '
        type: depromeet.ohgzoo.iam.member.NoExistsMemberException
      postNotExists:
        code: 401
        msg: '글이 존재하지 않습니다. '
        type: depromeet.ohgzoo.iam.posts.PostsNotFoundException